-- Populate countries table with comprehensive list of world countries
-- Use INSERT OR IGNORE to avoid duplicate inserts across re-runs

-- Insert comprehensive list of world countries
INSERT OR IGNORE INTO countries (code, name) VALUES
  -- North America
  ('US', 'United States'),
  ('CA', 'Canada'),
  ('MX', 'Mexico'),
  ('GT', 'Guatemala'),
  ('BZ', 'Belize'),
  ('SV', 'El Salvador'),
  ('HN', 'Honduras'),
  ('NI', 'Nicaragua'),
  ('CR', 'Costa Rica'),
  ('PA', 'Panama'),
  
  -- South America  
  ('BR', 'Brazil'),
  ('AR', 'Argentina'),
  ('CL', 'Chile'),
  ('PE', 'Peru'),
  ('CO', 'Colombia'),
  ('VE', 'Venezuela'),
  ('EC', 'Ecuador'),
  ('BO', 'Bolivia'),
  ('PY', 'Paraguay'),
  ('UY', 'Uruguay'),
  ('GY', 'Guyana'),
  ('SR', 'Suriname'),
  ('GF', 'French Guiana'),
  
  -- Caribbean
  ('CU', 'Cuba'),
  ('JM', 'Jamaica'),
  ('HT', 'Haiti'),
  ('DO', 'Dominican Republic'),
  ('PR', 'Puerto Rico'),
  ('TT', 'Trinidad and Tobago'),
  ('BB', 'Barbados'),
  ('BS', 'Bahamas'),
  
  -- Europe
  ('GB', 'United Kingdom'),
  ('FR', 'France'),
  ('DE', 'Germany'),
  ('IT', 'Italy'),
  ('ES', 'Spain'),
  ('PT', 'Portugal'),
  ('NL', 'Netherlands'),
  ('BE', 'Belgium'),
  ('CH', 'Switzerland'),
  ('AT', 'Austria'),
  ('SE', 'Sweden'),
  ('NO', 'Norway'),
  ('DK', 'Denmark'),
  ('FI', 'Finland'),
  ('IS', 'Iceland'),
  ('IE', 'Ireland'),
  ('PL', 'Poland'),
  ('CZ', 'Czech Republic'),
  ('SK', 'Slovakia'),
  ('HU', 'Hungary'),
  ('RO', 'Romania'),
  ('BG', 'Bulgaria'),
  ('GR', 'Greece'),
  ('TR', 'Türkiye'),
  ('CY', 'Cyprus'),
  ('HR', 'Croatia'),
  ('SI', 'Slovenia'),
  ('RS', 'Serbia'),
  ('ME', 'Montenegro'),
  ('BA', 'Bosnia and Herzegovina'),
  ('MK', 'North Macedonia'),
  ('AL', 'Albania'),
  ('EE', 'Estonia'),
  ('LV', 'Latvia'),
  ('LT', 'Lithuania'),
  ('BY', 'Belarus'),
  ('UA', 'Ukraine'),
  ('MD', 'Moldova'),
  ('RU', 'Russia'),
  ('MT', 'Malta'),
  ('LU', 'Luxembourg'),
  ('LI', 'Liechtenstein'),
  ('AD', 'Andorra'),
  ('MC', 'Monaco'),
  ('SM', 'San Marino'),
  ('VA', 'Vatican City'),
  
  -- Asia
  ('CN', 'China'),
  ('JP', 'Japan'),
  ('KR', 'South Korea'),
  ('KP', 'North Korea'),
  ('MN', 'Mongolia'),
  ('IN', 'India'),
  ('PK', 'Pakistan'),
  ('BD', 'Bangladesh'),
  ('LK', 'Sri Lanka'),
  ('NP', 'Nepal'),
  ('BT', 'Bhutan'),
  ('MV', 'Maldives'),
  ('MM', 'Myanmar'),
  ('TH', 'Thailand'),
  ('LA', 'Laos'),
  ('KH', 'Cambodia'),
  ('VN', 'Vietnam'),
  ('MY', 'Malaysia'),
  ('SG', 'Singapore'),
  ('ID', 'Indonesia'),
  ('PH', 'Philippines'),
  ('BN', 'Brunei'),
  ('TL', 'East Timor'),
  ('TW', 'Taiwan'),
  ('AF', 'Afghanistan'),
  ('UZ', 'Uzbekistan'),
  ('KZ', 'Kazakhstan'),
  ('KG', 'Kyrgyzstan'),
  ('TJ', 'Tajikistan'),
  ('TM', 'Turkmenistan'),
  ('IR', 'Iran'),
  ('IQ', 'Iraq'),
  ('SY', 'Syria'),
  ('LB', 'Lebanon'),
  ('JO', 'Jordan'),
  ('IL', 'Israel'),
  ('PS', 'Palestine'),
  ('SA', 'Saudi Arabia'),
  ('YE', 'Yemen'),
  ('OM', 'Oman'),
  ('AE', 'United Arab Emirates'),
  ('QA', 'Qatar'),
  ('BH', 'Bahrain'),
  ('KW', 'Kuwait'),
  ('AM', 'Armenia'),
  ('AZ', 'Azerbaijan'),
  ('GE', 'Georgia'),
  
  -- Africa
  ('NG', 'Nigeria'),
  ('EG', 'Egypt'),
  ('ZA', 'South Africa'),
  ('KE', 'Kenya'),
  ('UG', 'Uganda'),
  ('TZ', 'Tanzania'),
  ('ET', 'Ethiopia'),
  ('GH', 'Ghana'),
  ('CI', 'Côte d''Ivoire'),
  ('CM', 'Cameroon'),
  ('MG', 'Madagascar'),
  ('AO', 'Angola'),
  ('MZ', 'Mozambique'),
  ('ML', 'Mali'),
  ('BF', 'Burkina Faso'),
  ('NE', 'Niger'),
  ('MW', 'Malawi'),
  ('ZM', 'Zambia'),
  ('ZW', 'Zimbabwe'),
  ('BW', 'Botswana'),
  ('NA', 'Namibia'),
  ('SZ', 'Eswatini'),
  ('LS', 'Lesotho'),
  ('RW', 'Rwanda'),
  ('BI', 'Burundi'),
  ('DJ', 'Djibouti'),
  ('ER', 'Eritrea'),
  ('SO', 'Somalia'),
  ('SD', 'Sudan'),
  ('SS', 'South Sudan'),
  ('TD', 'Chad'),
  ('CF', 'Central African Republic'),
  ('CG', 'Republic of the Congo'),
  ('CD', 'Democratic Republic of the Congo'),
  ('GA', 'Gabon'),
  ('GQ', 'Equatorial Guinea'),
  ('ST', 'São Tomé and Príncipe'),
  ('SL', 'Sierra Leone'),
  ('LR', 'Liberia'),
  ('GN', 'Guinea'),
  ('GW', 'Guinea-Bissau'),
  ('SN', 'Senegal'),
  ('GM', 'Gambia'),
  ('CV', 'Cape Verde'),
  ('MR', 'Mauritania'),
  ('DZ', 'Algeria'),
  ('TN', 'Tunisia'),
  ('LY', 'Libya'),
  ('MA', 'Morocco'),
  ('EH', 'Western Sahara'),
  ('MU', 'Mauritius'),
  ('SC', 'Seychelles'),
  ('KM', 'Comoros'),
  
  -- Oceania
  ('AU', 'Australia'),
  ('NZ', 'New Zealand'),
  ('PG', 'Papua New Guinea'),
  ('FJ', 'Fiji'),
  ('SB', 'Solomon Islands'),
  ('NC', 'New Caledonia'),
  ('VU', 'Vanuatu'),
  ('WS', 'Samoa'),
  ('TO', 'Tonga'),
  ('TV', 'Tuvalu'),
  ('KI', 'Kiribati'),
  ('NR', 'Nauru'),
  ('PW', 'Palau'),
  ('FM', 'Micronesia'),
  ('MH', 'Marshall Islands'),
  ('AS', 'American Samoa'),
  ('GU', 'Guam'),
  ('MP', 'Northern Mariana Islands'),
  ('PF', 'French Polynesia'),
  ('CK', 'Cook Islands'),
  ('NU', 'Niue'),
  ('TK', 'Tokelau');