name = "flare360-ingest"
main = "src/index.ts"
compatibility_date = "2024-10-01"

account_id = "1e54c42267499cd9093c467c8b5517d1"

[[d1_databases]]
binding = "DB"
database_name = "dcom360-db"
database_id = "aae8e15b-bb6a-4f16-9e2d-e63ec2ae9c20"

[[kv_namespaces]]
binding = "CACHE"
id = "46818e79770044efa2e863ca0b0f465a"

[vars]
INGEST_TOKEN = "dev-token-123" # set via `wrangler secret put INGEST_TOKEN` in production

[env.staging]
[env.staging.vars]
INGEST_TOKEN = "dev-token-123"
[[env.staging.d1_databases]]
binding = "DB"
database_name = "dcom360-db"
database_id = "aae8e15b-bb6a-4f16-9e2d-e63ec2ae9c20"
[[env.staging.kv_namespaces]]
binding = "CACHE"
id = "46818e79770044efa2e863ca0b0f465a"

[env.production]
# Use Cloudflare Secret for INGEST_TOKEN in production (do not set as plain var)
[[env.production.d1_databases]]
binding = "DB"
database_name = "dcom360-db"
database_id = "aae8e15b-bb6a-4f16-9e2d-e63ec2ae9c20"
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "46818e79770044efa2e863ca0b0f465a"
