account_id = "1e54c42267499cd9093c467c8b5517d1"
name = "dcom360-worker"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[vars]
ENV = "dev"
ENV_ORIGIN = "https://dcom360-frontend.pages.dev" # tightened CORS for production frontend
[[d1_databases]]
binding = "DB"
database_name = "dcom360-db"
database_id = "aae8e15b-bb6a-4f16-9e2d-e63ec2ae9c20"

[[kv_namespaces]]
binding = "CACHE"
id = "46818e79770044efa2e863ca0b0f465a"
