name: Deploy Workers and Smoke Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  WORKER_URL: ${{ vars.WORKER_URL }}
  INGEST_URL: ${{ vars.INGEST_URL }}
  PAGES_PROJECT_NAME: ${{ vars.PAGES_PROJECT_NAME }}
  INGEST_TOKEN: ${{ secrets.INGEST_TOKEN }}

jobs:
  deploy-ingest:
    name: Deploy Ingestion Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            ingest-worker/package-lock.json
      - name: Install dependencies (ingest-worker)
        working-directory: ingest-worker
        run: npm install --no-audit --no-fund
      - name: Deploy ingest-worker
        working-directory: ingest-worker
        run: npx wrangler@4 deploy --env production
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
      - name: Configure ingest secret (production)
        working-directory: ingest-worker
        env:
          INGEST_TOKEN: ${{ env.INGEST_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: |
          # Store the ingest token as a Cloudflare Worker secret (production env)
          # Deploying first removes any legacy plain var binding so the secret name won't conflict.
          set -euo pipefail
          : "${INGEST_TOKEN:?Missing INGEST_TOKEN}"
          printf "%s" "$INGEST_TOKEN" | npx wrangler@4 secret put INGEST_SECRET --env production

  deploy-api:
    name: Deploy API Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            worker/package-lock.json
      - name: Install dependencies (worker)
        working-directory: worker
        run: npm ci --no-audit --no-fund
      - name: Set MAPTILER_KEY secret (production)
        working-directory: worker
        env:
          VITE_MAPTILER_KEY: ${{ secrets.VITE_MAPTILER_KEY }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: |
          set -euo pipefail
          : "${VITE_MAPTILER_KEY:?Missing VITE_MAPTILER_KEY GitHub secret}"
          printf "%s" "$VITE_MAPTILER_KEY" | npx wrangler@4 secret put MAPTILER_KEY --env production
      - name: Deploy worker
        working-directory: worker
        run: npx wrangler@4 deploy --env production
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
      - name: Install Wrangler CLI
        run: npm install -g wrangler@4
      - name: Apply D1 migrations (production)
        working-directory: worker
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
        run: |
          bash scripts/run-migrations.sh dcom360-db --remote

  smoke-test:
    name: Post-deploy smoke tests
    runs-on: ubuntu-latest
    needs: [deploy-ingest, deploy-api]
    steps:
      - name: Ensure jq is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Prepare URLs
        id: prep
        run: |
          API_URL="${WORKER_URL:-https://flare360-worker.samuel-1e5.workers.dev}"
          # Prefer the production environment domain for the ingest worker.
          # If INGEST_URL is set to the non-prod workers.dev subdomain, rewrite to -production.
          RAW_ING_URL="${INGEST_URL:-https://flare360-ingest-production.samuel-1e5.workers.dev}"
          if echo "$RAW_ING_URL" | grep -q '^https://flare360-ingest\.samuel-1e5\.workers\.dev$'; then
            ING_URL="https://flare360-ingest-production.samuel-1e5.workers.dev"
          else
            ING_URL="$RAW_ING_URL"
          fi
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT
          echo "ing_url=$ING_URL" >> $GITHUB_OUTPUT
      - name: Check /api/health
        run: |
          set -euo pipefail
          code=$(curl -s -o health.json -w "%{http_code}" "${{ steps.prep.outputs.api_url }}/api/health")
          test "$code" = "200"
          grep -q '"success":\s*true' health.json
      - name: Check /api/config has map key
        run: |
          set -euo pipefail
          code=$(curl -s -o cfg.json -w "%{http_code}" "${{ steps.prep.outputs.api_url }}/api/config")
          test "$code" = "200"
          jq -e '.success == true and .data.has_key == true and (.data.map_style | length > 0)' cfg.json >/dev/null
      - name: Check /api/disasters/summary
        run: |
          set -euo pipefail
          code=$(curl -s -o summary.json -w "%{http_code}" "${{ steps.prep.outputs.api_url }}/api/disasters/summary")
          test "$code" = "200"
          grep -q '"success":\s*true' summary.json
          grep -q '"totals"' summary.json
      - name: Check /api/countries returns multiple
        run: |
          set -euo pipefail
          code=$(curl -s -o countries.json -w "%{http_code}" "${{ steps.prep.outputs.api_url }}/api/countries")
          test "$code" = "200"
          jq -e '.success == true' countries.json >/dev/null
          COUNT=$(jq '.data | length' countries.json)
          echo "Country count: $COUNT"
          [ "$COUNT" -gt 1 ]
      - name: OPTIONS on ingest endpoint
        run: |
          set -euo pipefail
          code=$(curl -s -o /dev/null -w "%{http_code}" -X OPTIONS "${{ steps.prep.outputs.ing_url }}/ingest/gdacs")
          test "$code" = "204"
      - name: Trigger GDACS ingest
        run: |
          set -euo pipefail
          # small delay to allow propagation after deploy
          sleep 3
          : "${INGEST_TOKEN:?Missing INGEST_TOKEN secret}"
          max_attempts=5
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            code=$(curl -s -o resp.json -w "%{http_code}" -X POST "${{ steps.prep.outputs.ing_url }}/ingest/gdacs" -H "authorization: Bearer ${INGEST_TOKEN}" || true)
            echo "HTTP_CODE=$code"
            if [ "$code" = "200" ] && grep -q '"success":\s*true' resp.json; then
              break
            fi
            if grep -q 'Too many API requests' resp.json || grep -q 'INGEST_ERROR' resp.json; then
              echo "Rate limited or transient error. Retrying in $((attempt*2)) seconds..."
              sleep $((attempt*2))
              attempt=$((attempt+1))
            else
              echo "Response body:" && cat resp.json || true
              exit 1
            fi
          done
          if [ $attempt -gt $max_attempts ]; then
            echo "Failed after $max_attempts attempts."
            exit 1
          fi

# VolcanoDiscovery RSS feed removed - only GDACS and ReliefWeb feeds are now supported

  pages-deploy:
    name: Deploy Pages (production)
    runs-on: ubuntu-latest
    needs: [deploy-api, smoke-test, frontend-e2e]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
      - name: Ensure jq is installed
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Resolve Pages project name
        id: project
        run: |
          NAME="${PAGES_PROJECT_NAME:-flare360-frontend}"
          echo "name=$NAME" >> $GITHUB_OUTPUT
      - name: Ensure Pages project exists
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          set -euo pipefail
          NAME="${{ steps.project.outputs.name }}"
          # List existing projects; create if missing
          if ! npx wrangler@4 pages project list | grep -q "\b$NAME\b"; then
            npx wrangler@4 pages project create "$NAME" --production-branch main
          fi
      - name: Build frontend
        working-directory: frontend
        env:
          VITE_API_BASE: ${{ vars.WORKER_URL }}
          VITE_MAPTILER_KEY: ${{ secrets.VITE_MAPTILER_KEY }}
        run: |
          npm ci --no-audit --no-fund
          npm run build
      - name: Deploy to Pages (production)
        run: |
          npx wrangler@4 pages deploy frontend/dist --project-name "${{ steps.project.outputs.name }}" --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ env.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
      - name: Invalidate preview deployments (best-effort)
        run: |
          set -euo pipefail
          PROJECT="${{ steps.project.outputs.name }}"
          # List deployments and delete previews (best-effort; ignore failures if API differs)
          curl -s -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$PROJECT/deployments" \
            | jq -r '.result[] | select(.environment=="preview") | .id' > ids.txt || true
          while read -r id; do
            [ -n "$id" ] || continue
            echo "Deleting preview deployment $id"
            curl -s -X DELETE -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$PROJECT/deployments/$id" || true
          done < ids.txt

  frontend-e2e:
    name: Frontend E2E (Playwright)
    runs-on: ubuntu-latest
    needs: [deploy-api]
    env:
      VITE_API_BASE: ${{ vars.WORKER_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
      - name: Install deps and browsers
        working-directory: frontend
        run: |
          npm ci --no-audit --no-fund
          npx playwright install --with-deps chromium
      - name: Run Playwright smoke
        working-directory: frontend
        env:
          VITE_API_BASE: ${{ env.VITE_API_BASE }}
        run: |
          npx playwright test
      
